/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Custom.MyComboBoxRenderer;
import DAO.BanAnDAO;
import DAO.HoaDonDAO;
import DAO.LoaiThucDonDAO;
import DAO.ThucDonDAO;
import POJO.BanAn;
import POJO.LoaiThucDon;
import POJO.ThucDon;
import UIS.MsgBox;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Nham Ngo
 */
public class frmOrder extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmOrder
     */
    HoaDonDAO dao;
    BanAnDAO daoBanAn;
    LoaiThucDonDAO daoLoaiThucDon;
    ThucDonDAO daoThucDon;
    static int MaBA;
    public frmOrder() {

        initComponents();
        dao = new HoaDonDAO();
        daoLoaiThucDon = new LoaiThucDonDAO();
        daoThucDon = new ThucDonDAO();
        daoBanAn = new BanAnDAO();
        cboLoaiThucDon.setRenderer(new MyComboBoxRenderer("Vui lòng chọn loại món ăn"));
        cboLoaiThucDon.setSelectedIndex(-1);
        cboThucDon.setRenderer(new MyComboBoxRenderer("Vui lòng chọn món ăn"));
        cboThucDon.setSelectedIndex(-1);
        loadTable();
        loadLoaiMonAn();
        XuKienSelectcboLoaiThucDon();
    }

    public void loadLoaiMonAn() {
        DefaultComboBoxModel def = (DefaultComboBoxModel) cboLoaiThucDon.getModel();
        def.removeAllElements();
        try {
            for (LoaiThucDon ltd : daoLoaiThucDon.selectAll()) {
                def.addElement(ltd);

            }
        } catch (Exception e) {
        }
        cboLoaiThucDon.setSelectedIndex(-1);
    }

    void XuKienSelectcboLoaiThucDon() {
        cboLoaiThucDon.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    LoaiThucDon selectedItem = (LoaiThucDon)event.getItem();
                    System.out.println(selectedItem.getTen());
                    System.out.println(selectedItem.getMaLoaiTD());
                    loadMonAnByLoaiMA(selectedItem.getMaLoaiTD());
                    
                }
            }
        });
    }

    public void loadMonAnByLoaiMA(int id) {
        DefaultComboBoxModel def = (DefaultComboBoxModel) cboThucDon.getModel();
        def.removeAllElements();
        try {
            for (ThucDon ltd : daoThucDon.selectByLoaiMA(id)) {
                def.addElement(ltd);
            }
        } catch (Exception e) {
        }
        cboThucDon.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnBanAn = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCacMonDaGoi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnGoiMon = new javax.swing.JButton();
        btnXoaMon = new javax.swing.JButton();
        cboLoaiThucDon = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboThucDon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        btnGopBan = new javax.swing.JButton();
        btnChuyenBan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblSoBan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTrangThaiBan = new javax.swing.JLabel();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bàn ăn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout pnBanAnLayout = new javax.swing.GroupLayout(pnBanAn);
        pnBanAn.setLayout(pnBanAnLayout);
        pnBanAnLayout.setHorizontalGroup(
            pnBanAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        pnBanAnLayout.setVerticalGroup(
            pnBanAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnBanAn);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gọi món", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Các món ăn đã gọi"));

        tblCacMonDaGoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên món", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tblCacMonDaGoi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        jLabel1.setText("Tổng tiền:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("0 VNĐ");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(0, 51, 255));
        btnThanhToan.setText("Thanh toán");

        btnGoiMon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGoiMon.setText("Gọi món");
        btnGoiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiMonActionPerformed(evt);
            }
        });

        btnXoaMon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaMon.setText("Xóa món");

        cboLoaiThucDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoaiThucDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiThucDonActionPerformed(evt);
            }
        });
        cboLoaiThucDon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboLoaiThucDonPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chọn loại:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Chọn món:");

        cboThucDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboThucDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboThucDonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng:");

        spinSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spinSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnGopBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGopBan.setText("Gộp bàn");

        btnChuyenBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChuyenBan.setText("Chuyển bàn");
        btnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số bàn:");

        lblSoBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoBan.setForeground(new java.awt.Color(255, 0, 51));
        lblSoBan.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái:");

        lblTrangThaiBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangThaiBan.setText("Sẵn sàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGoiMon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaMon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChuyenBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGopBan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSoBan)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTrangThaiBan))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboLoaiThucDon, 0, 219, Short.MAX_VALUE)
                                .addComponent(cboThucDon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoaiThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTrangThaiBan)
                    .addComponent(jLabel7)
                    .addComponent(lblSoBan)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnThanhToan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiMonActionPerformed
        // TODO add your handling code here:
        if (this.lblSoBan.getText().trim() == "0") {
            MsgBox.alert(this, "Phải chọn bàn để gọi món!");
        } else {

        }
    }//GEN-LAST:event_btnGoiMonActionPerformed
    void loadTable() {
        pnBanAn.setLayout(new GridLayout(daoBanAn.selectAll().size() / 3, 3));
        for (BanAn ba : daoBanAn.selectAll()) {
            JButton button = new JButton("Bàn " + ba.getMaBan());
            button.setPreferredSize(new Dimension(40, 40));
            if (ba.getTrangThai().equals("Có người")) {
                button.setIcon(new ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\ico_trong.png"));
            } else if (ba.getTrangThai().equals("Hư")) {
                button.setIcon(new ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\ico_hu.png"));
            }
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    lblSoBan.setText(button.getText().substring(4));
                    
                }

            });
            pnBanAn.add(button);
        }
    }
    private void cboLoaiThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiThucDonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboLoaiThucDonActionPerformed

    private void cboLoaiThucDonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboLoaiThucDonPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cboLoaiThucDonPropertyChange

    private void cboThucDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboThucDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboThucDonMouseClicked

    private void btnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuyenBanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBan;
    private javax.swing.JButton btnGoiMon;
    private javax.swing.JButton btnGopBan;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoaMon;
    private javax.swing.JComboBox<String> cboLoaiThucDon;
    private javax.swing.JComboBox<String> cboThucDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSoBan;
    private javax.swing.JLabel lblTrangThaiBan;
    private javax.swing.JPanel pnBanAn;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tblCacMonDaGoi;
    // End of variables declaration//GEN-END:variables
}
