/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.QuanLy;

import Custom.MyComboBoxRenderer;
import Custom.MyDialog;
import Custom.MyFileChooser;
import Custom.XuLyFileExcel;
import DAO.LoaiThucDonDAO;
import DAO.ThucDonDAO;
import POJO.HoaDon;
import DAO.HoaDonDAO;
import POJO.LoaiThucDon;
import POJO.ThucDon;
import java.io.FileOutputStream;
import java.io.IOException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DatasetUtilities;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import org.jfree.chart.ChartUtilities;
import UIS.MsgBox;
import com.itextpdf.text.BadElementException;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.image.BufferedImage;
import java.io.File;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Image;
import java.awt.Desktop;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Nham Ngo
 */
public class frmQLDoanhThu extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFood
     */
    //Xóa
    //Sữa
    HoaDonDAO dao;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    private JFreeChart barChart;

    public frmQLDoanhThu() {
        initComponents();
        dao = new HoaDonDAO();
        tbHoaDon.setAutoCreateRowSorter(true);
        order();
        LocalDate currentDate = LocalDate.now();
        Date dateTo = Date.from(currentDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        LocalDate lastMonthDate = currentDate.minusMonths(1);
        Date dateForm = Date.from(lastMonthDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        dtcFrom.setDate(dateForm);
        dtcTo.setDate(dateTo);
    }

    void order() {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbHoaDon.getModel());
        tbHoaDon.setRowSorter(sorter);
        tbHoaDon.getTableHeader().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int column = tbHoaDon.columnAtPoint(e.getPoint());
                sorter.toggleSortOrder(column);
                sorter.sort();
            }
        });
    }

    void fillToTable(List<HoaDon> a) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        SimpleDateFormat newFormat = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel model = (DefaultTableModel) tbHoaDon.getModel();
        model.setRowCount(0);
        for (HoaDon p : a) {
            try {
                Date date = format.parse(p.getNgayTao());
                model.addRow(new Object[]{p.getMaHD(), newFormat.format(date), p.getMaNV(), p.getMaBan(), p.getTongTien(), p.getTrangThai()});
            } catch (ParseException ex) {
                 model.addRow(new Object[]{p.getMaHD(), p.getNgayTao(), p.getMaNV(), p.getMaBan(), p.getTongTien(), p.getTrangThai()});
                Logger.getLogger(frmQLDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }

    void Sort() {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbHoaDon.getModel());
        tbHoaDon.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        int columnIndexToSort = 1;
        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        sorter.sort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cboNgay = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dtcFrom = new com.toedter.calendar.JDateChooser();
        dtcTo = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnXem = new javax.swing.JButton();
        txtTong = new javax.swing.JLabel();
        txtTong1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TrongNam = new com.toedter.calendar.JYearChooser();
        btnXem1 = new javax.swing.JButton();
        jpnItem = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setTitle("QUẢN LÝ HÓA ĐƠN");

        cboNgay.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cboNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp theo ngày", "Ngày mới nhất", "Ngày cũ nhất" }));
        cboNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNgayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Từ:");

        dtcFrom.setDateFormatString("dd/MM/yyyy");

        dtcTo.setDateFormatString("dd/MM/yyyy");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Đến:");

        pnlReport.setLayout(new javax.swing.BoxLayout(pnlReport, javax.swing.BoxLayout.LINE_AXIS));

        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaHD", "NgayTao", "MaNV", "MaBan", "TongTien", "TrangThai"
            }
        ));
        jScrollPane1.setViewportView(tbHoaDon);

        pnlReport.add(jScrollPane1);

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\icons8-export-csv-20.png")); // NOI18N
        jButton1.setText("Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnXem.setIcon(new javax.swing.ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\icons8-eye-30.png")); // NOI18N
        btnXem.setText("Xem");
        btnXem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemMouseClicked(evt);
            }
        });
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        txtTong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTong.setText("0 VND");

        txtTong1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTong1.setText("Tổng Doanh thu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 357, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(dtcFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtcTo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTong1)
                    .addComponent(txtTong)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Danh sách", jPanel2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Chọn Năm : ");

        btnXem1.setIcon(new javax.swing.ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\icons8-eye-30.png")); // NOI18N
        btnXem1.setText("Xem");
        btnXem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXem1ActionPerformed(evt);
            }
        });

        jpnItem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biểu đổ doanh thu theo năm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jpnItem.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpnItemLayout = new javax.swing.GroupLayout(jpnItem);
        jpnItem.setLayout(jpnItemLayout);
        jpnItemLayout.setHorizontalGroup(
            jpnItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
        );
        jpnItemLayout.setVerticalGroup(
            jpnItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Learn\\period 2\\Java\\QuanLyNhaHangg\\src\\Assets\\icons\\icons8-export-30.png")); // NOI18N
        jButton2.setText("In hình ảnh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrongNam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXem1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(370, 370, 370))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(TrongNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXem1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jpnItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)))
        );

        jTabbedPane1.addTab("Sơ đồ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNgayActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboNgayActionPerformed

    private void btnXemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemMouseClicked
    private void Tong() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Tong = 0;
        for (int i = 0; i < tbHoaDon.getRowCount(); i++) {
            Object obj = tbHoaDon.getValueAt(i, 4);
            if (obj != null && obj instanceof Number) {
                Tong += ((Number) obj).intValue();
            }
        }
        txtTong.setText(x.format(Tong) + " VNĐ");
    }
    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY");
        Date jCalDate1=dtcFrom.getDate();
        Date jCalDate2=dtcTo.getDate();
        System.out.println("date to");
        if (dao.FIND_TongTien(jCalDate1, jCalDate2) == null)
            MsgBox.alert(this, "Những ngày này không có giao dịch ");
        else {
            fillToTable(dao.FIND_TongTien(jCalDate1, jCalDate2));
            Tong();
        }
    }//GEN-LAST:event_btnXemActionPerformed
    private void xuLyXuatFileExcel() {
        XuLyFileExcel xuatFile = new XuLyFileExcel();
        xuatFile.xuatExcel(tbHoaDon);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        xuLyXuatFileExcel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXem1ActionPerformed
        // TODO add your handling code here:
        int Nam = TrongNam.getYear();
        if (dao.SelectYear(Nam) == null)
            MsgBox.alert(this, "Những ngày này không giao dịch ");
        else {
            data(Nam);
        }
    }//GEN-LAST:event_btnXem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        in();
    }//GEN-LAST:event_jButton2ActionPerformed
   void in() {
        try {
            ChartUtilities.saveChartAsPNG(new File("D:\\test\\chart.png"), barChart, 1000, 800);
            System.out.println("Saved chart as PNG image.");
        } catch (IOException e) {
            System.err.println("Error saving PNG image: " + e.getMessage());
        }
        File imageFile = new File("D:\\test\\chart.png");
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(imageFile);
            } else {
                System.out.println("Desktop is not supported!");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    

    public void data(int Nam) {
        List<HoaDon> listItem = dao.SelectYear(Nam);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listItem != null) {
            for (HoaDon item : listItem) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
                try {
                    Date date = dateFormat.parse(item.getNgayTao());
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    int month = cal.get(Calendar.MONTH) + 1;
                    dataset.addValue((Number) item.getTongTien(), "Số Tiền", month);
                } catch (Exception e) {
                }

            }
            barChart = ChartFactory.createBarChart(
                    "Doanh Thu tháng Năm "+Nam,
                    "Tháng", "Số Tiền ",
                    dataset, PlotOrientation.VERTICAL, false, false, false);
            ChartPanel chartPanel = new ChartPanel(barChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(jpnItem.getWidth(), 367));
            chartPanel.setMouseWheelEnabled(true);
            jpnItem.removeAll();
            jpnItem.setLayout(new BorderLayout());
            jpnItem.add(chartPanel, BorderLayout.CENTER);
            jpnItem.validate();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser TrongNam;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXem1;
    private javax.swing.JComboBox<String> cboNgay;
    private com.toedter.calendar.JDateChooser dtcFrom;
    private com.toedter.calendar.JDateChooser dtcTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnItem;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JLabel txtTong;
    private javax.swing.JLabel txtTong1;
    // End of variables declaration//GEN-END:variables
}
